movagc/movag/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('movieapp.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)

    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

movagc/movieapp/urls.py
from django.urls import path
from . import views
app_name='movieapp'

urlpatterns = [

    path('',views.index,name='index'),
    path('movie/<int:movie_id>/',views.detail,name='detail'),
    path('add/',views.add_movie,name='add_movie'),
    path('update/<int:id>',views.update,name='update'),
    path('delete/<int:id>',views.delete,name='delete')
]

movagc/movieapp/models.py
from django.db import models

# Create your models here.
class Movie(models.Model):
    name=models.CharField(max_length=30)
    desc=models.TextField()
    year=models.IntegerField()
    img=models.ImageField(upload_to='gallery')

    def __str__(self):
        return self.name

movagc/movieapp/forms.py
from django import forms
from .models import Movie

class MovieForm(forms.ModelForm):
    class Meta:
        model=Movie
        fields=['name','desc','year','img']

movagc/movieapp/views.py
from django.shortcuts import render,redirect
from .models import Movie
from .forms import MovieForm

# Create your views here.
def index(request):
    movie=Movie.objects.all()
    context={
        'movie_list':movie
    }
    return render(request,'index.html',context)
def detail(request,movie_id):
    movie=Movie.objects.get(id=movie_id)
    return render(request,'detail.html',{'movie':movie})
def add_movie(request):
    if request.method=='POST':
        name =request.POST.get('name')
        desc = request.POST.get('desc')
        year= request.POST.get('year')
        img = request.FILES['img']
        movie=Movie(name=name,desc=desc,year=year,img=img)
        movie.save()
    return render(request,'add.html')

def update(request,id):
    movie=Movie.objects.get(id=id)
    form=MovieForm(request.POST or None,request.FILES,instance=movie)
    if form.is_valid():
        form.save()
        return redirect('/')
    return render(request,'edit.html',{'form':form,'movie':movie})

def delete(request,id):
    if request.method=='POST':
        movie=Movie.objects.get(id=id)
        movie.delete()
        return redirect('/')
    return render(request,'delete.html')

movagc/templates/add.html
<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <input type="text" name="name" placeholder="Enter Movie name"><br>
    <input type="text" name="desc" placeholder="Enter Movie Description"><br>
    <input type="text" name="year" placeholder="Enter Movie year"><br>
    <input type="file" name="img"><br>
    <input type="submit">

</form>

movagc/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Index</title>
     <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    <link rel="stylesheet" href="#">
    <link rel="stylesheet" href="{% static 'style.css' %}">
</head>
<body>
<!-- Image and text -->
<nav class="navbar navbar-dark bg-dark" style="background-color:tomato; font-size:37px;padding:14px 16px;text-align:center;color:white;">
  <a class="navbar-brand" href="#">

    Online Movie Store
  </a>
</nav>
{% block body %}
{% endblock %}
</body>
</html>

movagc/templates/delete.html
<form method="POST">
    {% csrf_token %}
Are you sure to delete this movie?
    <input type="submit">
</form>

movagc/templates/detail.html
{% extends 'base.html' %}

{% block body %}

<img src="{{movie.img.url}}" width="100" height="100">
{{movie.name}}<br>
{{movie.desc}}<br>
{{movie.year}}<br>
<a class="btn btn-warning" border-color='aqua' href="{% url 'movieapp:update' movie.id %}">update</a>
<a class="btn btn-danger" href="{% url 'movieapp:delete' movie.id %}">Delete</a>

{% endblock %}

movagc/templates/edit.html
{% extends 'base.html' %}

{% block body %}

<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
{{form.as_p}}
    <input type="submit">
</form>
{% endblock %}

movagc/templates/index.html
{% extends 'base.html' %}


{% block body %}


<div class="container">

  <div class="row">
    {%  for i in movie_list %}
    <div class="col-md-3">
<div class="card text-center border-2 border-warning" style="width:150px; height :auto;">
  <img class="card-img-top" src="{{i.img.url}}" height="200" width="200" alt="Card image cap">
  <div class="card-body">
    <a href="{% url 'movieapp:detail' i.id %}" class="btn btn-primary">{{i.name}}</a>
  </div>
</div>
    </div>
    {% endfor %}
  </div>

</div>













{% endblock %}